[2024-04-29T02:01:30.850+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T02:01:30.870+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T02:01:22.852905+00:00 [queued]>
[2024-04-29T02:01:30.877+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T02:01:22.852905+00:00 [queued]>
[2024-04-29T02:01:30.878+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T02:01:30.889+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validate_file> on 2024-04-29 02:01:22.852905+00:00
[2024-04-29T02:01:30.895+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=95) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T02:01:30.896+0000] {standard_task_runner.py:63} INFO - Started process 97 to run task
[2024-04-29T02:01:30.896+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'validate_file', 'manual__2024-04-29T02:01:22.852905+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_cab.py', '--cfg-path', '/tmp/tmpn51k6ldb']
[2024-04-29T02:01:30.899+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask validate_file
[2024-04-29T02:01:30.949+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.validate_file manual__2024-04-29T02:01:22.852905+00:00 [running]> on host b97262715cd8
[2024-04-29T02:01:31.032+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='validate_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T02:01:22.852905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T02:01:22.852905+00:00'
[2024-04-29T02:01:31.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T02:01:31.046+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-29T02:01:31.049+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-04-29T02:01:31.050+0000] {branch.py:36} INFO - Branch into False
[2024-04-29T02:01:31.050+0000] {skipmixin.py:178} INFO - Following branch False
[2024-04-29T02:01:31.052+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T02:01:31.060+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 37, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 194, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must be either None, a task ID, or an Iterable of IDs, but got 'bool'.
[2024-04-29T02:01:31.064+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_yellow_cab, task_id=validate_file, execution_date=20240429T020122, start_date=20240429T020130, end_date=20240429T020131
[2024-04-29T02:01:31.076+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task validate_file ('branch_task_ids' must be either None, a task ID, or an Iterable of IDs, but got 'bool'.; 97)
[2024-04-29T02:01:31.120+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T02:01:31.133+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class SnowflakeOperator. (This class is deprecated. Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`. Also, you can provide `hook_params={'warehouse': <warehouse>, 'database': <database>, 'role': <role>, 'schema': <schema>, 'authenticator': <authenticator>,'session_parameters': <session_parameters>}`.)
  result = cls.__new__(cls)

[2024-04-29T02:01:31.158+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T02:01:31.162+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
