[2024-04-30T09:10:50.951+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T09:10:50.976+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T09:05:08.400583+00:00 [queued]>
[2024-04-30T09:10:50.985+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T09:05:08.400583+00:00 [queued]>
[2024-04-30T09:10:50.986+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T09:10:51.008+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): load_data> on 2024-04-30 09:05:08.400583+00:00
[2024-04-30T09:10:51.020+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T09:10:51.024+0000] {standard_task_runner.py:63} INFO - Started process 189 to run task
[2024-04-30T09:10:51.020+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'load_data', 'manual__2024-04-30T09:05:08.400583+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpctdbgqdf']
[2024-04-30T09:10:51.025+0000] {standard_task_runner.py:91} INFO - Job 229: Subtask load_data
[2024-04-30T09:10:51.088+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.load_data manual__2024-04-30T09:05:08.400583+00:00 [running]> on host e9da19e9b640
[2024-04-30T09:10:51.190+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T09:05:08.400583+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T09:05:08.400583+00:00'
[2024-04-30T09:10:51.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T09:10:51.194+0000] {logging_mixin.py:188} INFO - passed engine creation
[2024-04-30T09:10:51.195+0000] {logging_mixin.py:188} INFO - enter for loop
[2024-04-30T09:10:51.196+0000] {logging_mixin.py:188} INFO - enter for loop
[2024-04-30T09:10:51.196+0000] {logging_mixin.py:188} INFO - enter for loop
[2024-04-30T09:10:51.197+0000] {logging_mixin.py:188} INFO - enter for loop
[2024-04-30T09:10:51.197+0000] {logging_mixin.py:188} INFO - enter if loop
[2024-04-30T09:10:51.197+0000] {logging_mixin.py:188} INFO - enter file_upload function
[2024-04-30T09:10:51.198+0000] {logging_mixin.py:188} INFO - read filepath
[2024-04-30T09:10:51.198+0000] {logging_mixin.py:188} INFO - /opt/***/dags/files/yellow_tripdata_2011-02.parquet
[2024-04-30T09:10:51.210+0000] {logging_mixin.py:188} INFO - (psycopg2.OperationalError) connection to server at "localhost" (::1), port 54320 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 54320 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-30T09:10:51.210+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T09:10:51.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T09:10:51.220+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_yellow_cab, task_id=load_data, execution_date=20240430T090508, start_date=20240430T091050, end_date=20240430T091051
[2024-04-30T09:10:51.250+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T09:10:51.271+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-30T09:10:51.272+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
