[2024-04-30T07:32:12.398+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T07:32:12.425+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_yellow_cab.request_file manual__2024-04-30T07:32:03.981275+00:00 [queued]>
[2024-04-30T07:32:12.434+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_yellow_cab.request_file manual__2024-04-30T07:32:03.981275+00:00 [queued]>
[2024-04-30T07:32:12.435+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T07:32:12.449+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): request_file> on 2024-04-30 07:32:03.981275+00:00
[2024-04-30T07:32:12.458+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T07:32:12.461+0000] {standard_task_runner.py:63} INFO - Started process 166 to run task
[2024-04-30T07:32:12.461+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_yellow_cab', 'request_file', 'manual__2024-04-30T07:32:03.981275+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp47u7m178']
[2024-04-30T07:32:12.464+0000] {standard_task_runner.py:91} INFO - Job 209: Subtask request_file
[2024-04-30T07:32:12.519+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_yellow_cab.request_file manual__2024-04-30T07:32:03.981275+00:00 [running]> on host 24535bbbd9a8
[2024-04-30T07:32:12.628+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_yellow_cab' AIRFLOW_CTX_TASK_ID='request_file' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T07:32:03.981275+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T07:32:03.981275+00:00'
[2024-04-30T07:32:12.629+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T07:32:27.781+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-04-30T07:32:27.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-30T07:32:27.832+0000] {process_utils.py:132} INFO - Sending 15 to group 166. PIDs of all processes in the group: [166]
[2024-04-30T07:32:27.833+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 166
[2024-04-30T07:32:27.848+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-30T07:32:29.261+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T07:32:29.471+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=166, status='terminated', exitcode=0, started='07:32:12') (166) terminated with exit code 0
